### ISSUE TITLE
단어 빈도수 측정 방식을 TF-IDF와 LDA를 활용하여 개선

### ISSUE THREAD

**Issue by rhgo1749** [refind-opensw/refind-web_history#13]
기존 빈도수 측정 방식은 단순 빈도수만 측정하여 중요하지 않은 단어라도 빈도수가 높게 나온다는 단점이 있었습니다.
  따라서 빈도수 측정방식을 멘토링때 조언 받은 TF-IDF + LDA를 이용한 빈도수 측정방식으로 개선이 필요합니다.
TF-IDF : https://wikidocs.net/31698
LDA : https://wikidocs.net/30708

**Comment by Sain-Tech** [comment]
확인하였습니다..!
