### ISSUE TITLE
개선된 방식으로 측정된 단어 빈도수에 따라 웹 페이지 주제 선정 기능 구현 필요

### ISSUE THREAD

**Issue by rhgo1749** [refind-opensw/refind-web_history#14]
#13에서 개선된 단어 빈도수에 Word2Vec의 similarity 함수를 사용하여 유사도를 측정해 미리 선별된 주제와 가장 유사한 단어를 주제로 선정하고 만일 모든단어의 유사도가 일정 기댓값보다 적을 시 기타 주제로 선정하면 될 것 같습니다.

**Comment by Sain-Tech** [comment]
유사도 기댓값은 직접 한번 검사를 수행 해 보고 결정을 해 봐야 될 것 같습니다.
예를 들어 유사도가 50% 미만이어도 부합하는 경우가 있을 수 있기 때문입니다..!
