### ISSUE TITLE
파이썬 실시간 데이터 연동을 위한 코드 개선

### ISSUE THREAD

**Issue by Sain-Tech** [refind-opensw/refind-web_history#20]
파이썬과 노드-클라이언트 간 실시간 데이터 연동을 위해서

기존의 라우터 전송 방식이 아닌

소켓(socket.io) 방식으로 이루어지도록 코드 개선 작업 진행 중 입니다.

**Comment by Sain-Tech** [comment]
소켓 방식으로 진행 한 결과, 데이터가 적을 때는 분석후 결과값 받아오는 것까지 잘 되지만
요청이 많을 경우 파이썬 측에서 지연되는 문제가 발생하는 것 같습니다.

데이터 전송 간격 타임을 좀 더 완화하거나, 분산 처리 방식을 도입해야 할 것 같습니다.

**Comment by rhgo1749** [comment]
확인하였습니다!
