### ISSUE TITLE
파이썬 코드 실행중 예외발생시 처리 코드 추가

### ISSUE THREAD

**Issue by rhgo1749** [refind-opensw/refind-web_history#21]
Node.js에서 파이썬 코드를 실행중 에러가 발생하면 전체 프로그램이 중단되는 문제가 발생하게됩니다. 
  따라서 에러가 발생하는 구간에 대하여 예외처리코드 추가가 필요합니다.

**Comment by Sain-Tech** [comment]
항상 고생 많으십니다.
확인했습니다..!
