### ISSUE TITLE
크롤링 불가 웹페이지 동적 크롤링

### ISSUE THREAD

**Issue by rhgo1749** [refind-opensw/refind-web_history#29]
기존 크롤링이 불가능해 기타주제로 분류되었던 페이지들을 동적 크롤링을 통해 크롤링 하는 것이 좋을 것 같습니다.
참고 : https://book.coalastudy.com/data-crawling/week-6/stage-2
https://baldeagle.tistory.com/40

**Comment by Sain-Tech** [comment]
확인이 늦어서 죄송합니다..! ㅜㅜ
항상 고생하십니다!
