### ISSUE TITLE
대주제 드래그 개선 필요

### ISSUE THREAD

**Issue by Sain-Tech** [refind-opensw/refind-web_history#6]
대주제 카테고리를 일반적인 마우스로 드래그 시 옆으로 넘어가지 않습니다.
일단 개선할 방법으로

1. 마우스 휠 세로 조작을 가로 조작으로 바꾼다. (세로 조작으로도 가로로 넘길 수 있게 함)
2. 대주제 카테고리 양 옆에 화살표 버튼을 만든다.

위 2가지를 생각해 두었는데, UI 깔끔하게 1번이 괜찮은 것 같은데

다른 의견 있으면 남겨주십시오..!

**Comment by rhgo1749** [comment]
흠...
1번은 직관적이지 못한 느낌이 들어요
차라리 2번이 좀 더 나은 것 같군요
다른대안으로 빈공간을 드래그시 옆으로 슬라이드 되게하는 것도 좋을 것 같아요

**Comment by Sain-Tech** [comment]
최대한 깔끔하게 반영해 보도록 하겠습니다.
